### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by desperado39** [EBosi/scPanBetaT2D#1]
Respected sir,
I am not able to find or clone the data possess in beta_raw.csv file. please provide the whole content of the file.

**Comment by EBosi** [comment]
I'm sorry for this issue. The repository has been archived on Figshare (https://figshare.com/articles/dataset/Data_from_Integration_of_single-cell_datasets_reveals_novel_transcriptomic_signatures_of_-cells_in_human_type_2_diabetes_/19754566), please try to download it from there as there should not be any issue.
Best regards,
EB
